config/routes.rb
Rails.application.routes.draw do
  resources :users
 root 'static_pages#home'
 get '/contact-us' , to: 'static_pages#contact'
 get '/about-us' , to: 'static_pages#about'
 get '/helloworld' , to: 'static_pages#helloworld'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: {maximum: 50 }
  validates :last_name, presence: true, length: {maximum: 50 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def helloworld
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Footer</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">FAQs<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Careers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Other cool things</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <li class="nav-item active">
       	<%= link_to("Homepage", root_path, {:class => "nav-link"}) %>
      </li>
      <li class="nav-item">
        <%= link_to("About", about_us_path, {:class => "nav-link"}) %>
      </li>
      <li class="nav-item">
        <%= link_to("Contact Us", contact_us_path, {:class => "nav-link"}) %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn my-2 my-sm-0" type="submit">Go</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>  
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About Us</h1>

<h2>Bespoke chairs from around the world</h2>

	<div class="aboutspiel">
		<p>Try-hard cardigan truffaut, mumblecore selvage keffiyeh sartorial vaporware master cleanse man braid austin ethical meh pork belly iceland. Tbh you probably haven't heard of them swag chillwave. Stumptown keffiyeh copper mug raclette tbh leggings, messenger bag cred kombucha poke asymmetrical letterpress gentrify cronut. PBR&B crucifix semiotics, lumbersexual cred shoreditch cray aesthetic kinfolk. Brooklyn leggings celiac, lomo hella twee cardigan beard single-origin coffee. Air plant listicle shabby chic, blue bottle 8-bit knausgaard four loko fixie 3 wolf moon austin art party lyft. Banjo tbh locavore fanny pack try-hard succulents.</p>

		<p>Shoreditch put a bird on it pork belly tbh. Cray mlkshk fap keffiyeh stumptown tofu, tumblr lumbersexual. Pitchfork tumeric helvetica messenger bag chicharrones offal, shoreditch fap williamsburg. Tote bag selfies fam, listicle small batch hammock fanny pack occupy vexillologist. Farm-to-table unicorn put a bird on it, fap brunch prism affogato. Succulents woke sartorial salvia, next level mlkshk activated charcoal kale chips retro. Tofu letterpress tumblr literally hashtag chambray, blue bottle mumblecore artisan everyday carry cred.
		</p>

		<p>
		Glossier banjo roof party lumbersexual pour-over quinoa. Before they sold out slow-carb art party migas, austin coloring book plaid letterpress polaroid celiac fashion axe authentic kogi intelligentsia. Paleo prism pitchfork, celiac chicharrones yr glossier food truck fam man braid kinfolk lyft fixie narwhal. Cred poutine jianbing pop-up selvage occupy 3 wolf moon lomo flannel, butcher chartreuse wayfarers tbh direct trade PBR&B. Vice iceland tbh, artisan neutra shabby chic succulents selfies occupy organic photo booth readymade fashion axe. Wayfarers mlkshk vegan ugh vice next level. Shabby chic kitsch hell of, scenester small batch fanny pack bicycle rights trust fund succulents squid tumeric vice 90's live-edge shoreditch.
		</p>
	</div>











<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>

<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/helloworld.html.erb
<h1>HELLO WORLD</h1>

app/views/static_pages/home.html.erb
<div class="col-12 headerquote">
  <h1 class="display-3">Welcome to the World of Chairs</h1>
  <p class="myblockquote"> We no longer think of chairs as technology; we just think of them as chairs. But there was a time when we hadn't worked out how many legs chairs should have, how tall they should be, and they would often 'crash' when we tried to use them.</p>
  <p class="author"> – Douglas Adams</p>
<div class="featurepost col-12">
  <h3 class="featurehead">Chair of the month</h3>
  <h2 class="chairname">The Hildenberg</h2>
</div>


</div>
<div class="container">
  <div class="row">
    <div class="chairtile col-6" id="europetile" >
      <h2>Chairs from Europe</h2>
    </div>
    <div class="chairtile col-6" id="USAtile">
      <h2>Chairs from America</h2>

    </div>
  </div>
  <div class="row">
    <div class="chairtile col-4" id="asiatile">
      <h2>Chairs from Asia</h2>

    </div>
    <div class="chairtile col-4" id="Austile">
      <h2>Chairs from Australia</h2>

    </div>
    <div class="chairtile col-4" id="poletiles" >
      <h2>Chairs from the Poles</h2>
    </div>
  </div>
</div>



<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>